# Generated by Django 4.2.16 on 2024-10-27 09:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('buying_price', models.DecimalField(decimal_places=2, max_digits=5)),
                ('selling_price', models.DecimalField(decimal_places=2, max_digits=5)),
                ('description', models.TextField()),
                ('quantity', models.IntegerField()),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
