# Generated by Django 4.2.16 on 2024-11-03 17:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255, unique=True)),
                ('buying_price', models.DecimalField(decimal_places=2, default=0.0, max_digits=6)),
                ('selling_price', models.DecimalField(decimal_places=2, default=0.0, max_digits=6)),
                ('manufacturer', models.TextField(max_length=255, null=True)),
                ('industry', models.TextField(choices=[('Agriculture', 'Agriculture'), ('Manufacturing', 'Manufacturing'), ('Technology', 'Technology'), ('Health', 'Health'), ('Food', 'Food'), ('Fashion', 'Fashion'), ('Construction', 'Construction'), ('Transport', 'Transport'), ('Uncategorized', 'Uncategorized')], default='Uncategorized', max_length=255)),
                ('quantity', models.IntegerField(default=0)),
            ],
            options={
                'db_table': 'products',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Sale',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(primary_key=True, serialize=False)),
                ('quantity', models.IntegerField(default=0)),
                ('discount', models.DecimalField(decimal_places=2, default=0.0, max_digits=6, null=True)),
                ('total_cost', models.DecimalField(decimal_places=2, default=0.0, max_digits=6)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='sales', to='inventory.product')),
            ],
            options={
                'db_table': 'sales',
                'ordering': ['created_at'],
            },
        ),
    ]
